# Generated by Django 4.0 on 2021-12-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('agencia', models.IntegerField(null=True)),
                ('numero_conta_corrente', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.IntegerField(null=True)),
                ('numero_conta_poupanca', models.IntegerField(null=True)),
                ('valor', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrente', models.FloatField(null=True)),
                ('credito', models.FloatField(null=True)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas_app.banco')),
                ('poupanca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas_app.poupanca')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('sobrenome', models.CharField(max_length=200, null=True)),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas_app.conta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
