# Generated by Django 4.0 on 2021-12-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poupanca',
            name='numero_conta',
        ),
    ]
