# Generated by Django 4.0 on 2021-12-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas_app', '0002_remove_poupanca_numero_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='conta',
        ),
        migrations.AddField(
            model_name='conta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas_app.cliente'),
        ),
    ]
